package view;

import java.util.ArrayList;
import java.util.HashMap;

import model.Customer;
import model.Order;
import model.Product;

import controller.ManageOrder;

//no.ntnu.course
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewOrder2Form.java
 *
 * Created on 29.sep.2011, 12:24:07
 */
/**
 *
 * @author Morten Vaale Noddeland
 */
@SuppressWarnings("serial")
public class NewOrder2Form extends javax.swing.JFrame {

	
	private Order order;
    /** Creates new form NewOrder2Form */
    public NewOrder2Form(Customer c) {
        initComponents();
        ManageOrder.addCustomerToDatabase(c);
        this.order = new Order(c);
        //ArrayList<String> productsInOrder = new ArrayList<String>();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        rightPanel = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();
        priceLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ny ordre");
        //setBounds(new java.awt.Rectangle(50, 50, 0, 0));
        setName("newOrderFrame"); // NOI18N
        setResizable(false);

        topPanel.setBackground(new java.awt.Color(120, 120, 120));
        topPanel.setPreferredSize(new java.awt.Dimension(780, 100));

        headerLabel.setFont(new java.awt.Font("Tahoma", 0, 36));
        headerLabel.setText("Ny ordre");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(headerLabel)
                .addContainerGap(333, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        leftPanel.setBackground(new java.awt.Color(238, 238, 238));
        leftPanel.setPreferredSize(new java.awt.Dimension(400, 387));

        searchField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        searchField.setText("Søk");
        searchField.setActionCommand("<Not Set>");
        searchField.setAlignmentX(0.0F);
        searchField.setAlignmentY(0.0F);
        searchField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 120, 120), 2), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10)));
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFieldKeyTyped(evt);
            }
        });

        leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        rightPanel.setBackground(new java.awt.Color(230, 230, 230));
        rightPanel.setPreferredSize(new java.awt.Dimension(400, 387));

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        bottomPanel.setBackground(new java.awt.Color(120, 120, 120));
        bottomPanel.setPreferredSize(new java.awt.Dimension(800, 100));

        priceLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("0,00,-");

        backButton.setText("Tilbake");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Fullfør");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGap(193, 193, 193)
                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(finishButton)
                .addContainerGap())
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(finishButton)
                    .addComponent(priceLabel))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                //.addContainerGap())
        ));

        pack();
    }// </editor-fold>
    
	/**
	 * Takes in a hashmap with product names and prices, packs them in
	 * a clickable JLabel, and shows them on screen
	 * @param products
	 */
    public void updateLeftPanel(ArrayList<Product> products) {
    	// Creates a JLabel array
    	ArrayList<javax.swing.JLabel> productList = new ArrayList<javax.swing.JLabel>();
    	for (int i=0; i<products.size(); i++){
        	// Create a new JLabel
        	javax.swing.JLabel temp = new javax.swing.JLabel();
            // Set JLabel dimensions, text, border and so on
        	final Product product = products.get(i);
            temp.setText(product.getName() + " " + product.formatPrice() + ",-");
            temp.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
            temp.setOpaque(true);
            temp.setPreferredSize(new java.awt.Dimension(140, 20));
            temp.setSize(new java.awt.Dimension(140, 20));
            temp.setVisible(true);
        	// Make it so that every other JLabel has a different background color than the previous
            int bg;
    		if (i % 2 == 0){
            	bg = 200;
            }
            else {
            	bg = 220;
            }
    		temp.setBackground(new java.awt.Color(bg, bg, bg));
    		// What method to call if the JLabel is clicked
            temp.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    productLabelMouseClicked(evt, product);
                }
            });
            // Add the JLabel to the array of JLabels
            productList.add(temp);
    	}
    	
        leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.removeAll();
        leftPanel.setLayout(leftPanelLayout);
        
        javax.swing.GroupLayout.ParallelGroup tempGroup = leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        tempGroup.addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE);
        for(int i = 0; i < productList.size(); i++) {
        	tempGroup.addComponent(productList.get(i), org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE);
        }
        tempGroup.addGroup(leftPanelLayout.createSequentialGroup()
            .addGap(79, 79, 79)
        );
        
        leftPanelLayout.setHorizontalGroup(
			leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(leftPanelLayout.createSequentialGroup()
				.addGroup(tempGroup)
			    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
			)
        );
        
        javax.swing.GroupLayout.SequentialGroup verticalTempGroup = leftPanelLayout.createSequentialGroup();
		verticalTempGroup.addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE);
		for(int i = 0; i < productList.size(); i++) {
			verticalTempGroup.addComponent(productList.get(i), org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE);
		}
		verticalTempGroup.addGap(86, 86, 86);
		verticalTempGroup.addContainerGap(235, Short.MAX_VALUE);
      
		leftPanelLayout.setVerticalGroup(
			leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(verticalTempGroup)
			);
		pack();
		searchField.grabFocus();
		searchField.setText(searchField.getText());
    }
    
    public void updateRightPanel() {
        // Set JLabel dimensions, text, border and so on
    	ArrayList<javax.swing.JLabel> orderList = new ArrayList<javax.swing.JLabel>();
        HashMap<Product, Integer> productsInOrder = ManageOrder.getProductsInOrder(order);
        // While there are more elements in the hashmap
        int counter = 0;
        for (Object o : productsInOrder.keySet()) {
        	// Create a new JLabel
        	javax.swing.JLabel temp = new javax.swing.JLabel();

        	if (o instanceof Product){
        		final Product product = (Product) o;
        		temp.setText(product.getName() + ": " + productsInOrder.get(product));
        		temp.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        		temp.setOpaque(true);
        		temp.setPreferredSize(new java.awt.Dimension(140, 20));
        		temp.setSize(new java.awt.Dimension(140, 20));
        		int bg;
        		if (counter % 2 == 0){
        			bg = 200;
        		}
        		else {
        			bg = 220;
        		}
        		temp.setBackground(new java.awt.Color(bg, bg, bg));
        		temp.setVisible(true);
        		
        		// What method to call if the JLabel is clicked
        		temp.addMouseListener(new java.awt.event.MouseAdapter() {
        			public void mouseClicked(java.awt.event.MouseEvent evt) {
        				orderLabelMouseClicked(evt, product);
        			}
        		});
        		orderList.add(temp);
        		counter++;
        	}
        }
        priceLabel.setText(""+ManageOrder.formatPrice(ManageOrder.getTotalPrice(order))+",-");
        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.removeAll();
        rightPanel.setLayout(rightPanelLayout);
        
        // Creates the Horizontal Parallel Group containing all the JLabels
        javax.swing.GroupLayout.ParallelGroup tempHorizontalGroup = rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        tempHorizontalGroup.addGap(0, 400, Short.MAX_VALUE);
        for(int i = 0; i < orderList.size(); i++) {
        	tempHorizontalGroup.addComponent(orderList.get(i), org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE);
        }
        // Creates the Vertical Parallel Group containing all the JLabels
        javax.swing.GroupLayout.SequentialGroup tempVerticalGroup = rightPanelLayout.createSequentialGroup();
        //tempVerticalGroup.addGap(0, 387, Short.MAX_VALUE);
        for(int i = 0; i < orderList.size(); i++) {
        	tempVerticalGroup.addComponent(orderList.get(i), org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE);
        }
        
        // Puts the groups created earlier into the right place in the rightPanelLayout
        rightPanelLayout.setHorizontalGroup(tempHorizontalGroup);
        rightPanelLayout.setVerticalGroup(tempVerticalGroup);
    }
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	NewOrderForm form = new NewOrderForm();
        form.setVisible(true);
        this.setVisible(false);
    }                                        

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	order.setStatus("Bestilt");
    	ManageOrder.submitOrderToDatabase(order);
    	System.out.println(order.getProductsInOrder().toString());
    	MainMenuForm form = new MainMenuForm();
        this.setVisible(false);
    	form.setVisible(true);
    }

    private void searchFieldKeyTyped(java.awt.event.KeyEvent evt) {
        this.updateLeftPanel(ManageOrder.getRelevantProducts(this.searchField.getText()));
    }
    private void productLabelMouseClicked(java.awt.event.MouseEvent evt, Product product) {   
    	ManageOrder.addOneMoreProductToOrdre(order, product);
    	this.updateRightPanel();
    }
    
    private void orderLabelMouseClicked(java.awt.event.MouseEvent evt, Product product) {                                          
//        productsInOrder.remove(productName);
    	this.updateRightPanel();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewOrder2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewOrder2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewOrder2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewOrder2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewOrder2Form(new Customer("Test", "testet", "676758598", "gate", "7878", "Oslo")).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton backButton;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.GroupLayout leftPanelLayout;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel topPanel;
    ArrayList<String> productsInOrder = new ArrayList<String>();
    // End of variables declaration
}
